version: "2"

services:
  # InfluxDB container
  influxdb:
    # Makes all ports accessible on the host for testing
    ports:
      - "8083:8083"

  # Grafana container
  grafana:
    ports:
      - "3000:3000"

  # H2 database
  h2:
    image: "nemerosa/h2:latest"
    ports:
      - "9082"
      - "8082"

  # Ontrack container
  ontrack:
    image: nemerosa/ontrack:${ONTRACK_VERSION}
    environment:
        PROFILE: acceptance
    volumes:
      # The /var/ontrack/conf on the DO machine is filled in from gradle/compose/ci/ontrack in the doEnv task
      - "/var/ontrack/conf:/var/ontrack/conf"
      # Better startup performances in CI and DO, do not use in Prod
      - "/dev/urandom:/dev/random"
    ports:
      - "443:443"
    links:
      - "h2:h2"
