version: "2.1"

services:
  # InfluxDB container
  influxdb:
    # Makes all ports accessible on the host for testing
    ports:
      - "8083"
      - "8086"

  # Grafana
  grafana:
    ports:
      - "3000"

  # H2 database
  h2:
    image: "nemerosa/h2:latest"
    ports:
      - "9082"
      - "8082"

  # Ontrack container
  ontrack:
    environment:
        PROFILE: acceptance
    volumes:
      - "./ci/ontrack:/var/ontrack/conf"
      # Better startup performances in CI and DO, do not use in Prod
      - "/dev/urandom:/dev/random"
    ports:
      - "443"
    links:
      - "h2:h2"
