# InfluxDB container
influxdb:
  image: influxdb:1.1-alpine
  environment:
    PRE_CREATE_DB: "ontrack"

# Grafana container
grafana:
  image: grafana/grafana:4.0.0
  links:
    - "influxdb:influxdb"

# Ontrack container
ontrack:
  image: nemerosa/ontrack:latest
  environment:
    JAVA_OPTIONS: "${JAVA_OPTIONS}"
  links:
    - "influxdb:influxdb"

# Postgresql database
postgresql:
  image: postgres:9.5.2
  environment:
    POSTGRES_DB      : ontrack
    POSTGRES_USER    : ontrack
    POSTGRES_PASSWORD: ontrack
  ports:
    - "5432"
