# InfluxDB container
influxdb:
  image: tutum/influxdb:0.9
  ports:
    - "8083"
    - "8086"
# Grafana container
grafana:
  image: grafana/grafana:latest
  ports:
    - "3000"
  links:
    - "influxdb:influxdb"
  volumes:
    - "./grafana/etc:/etc/grafana"
    - "./grafana/lib:/var/lib/grafana"
