# CI environment

# Local database
spring:
  datasource:
    url: "jdbc:h2:./database/data;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DEFRAG_ALWAYS=TRUE"

# SSL with self signed certificate
server:
  port: 443
  ssl:
    enabled: true
    key-store: "acceptance.jks"
    key-store-password: ontrack
    key-password: ontrack

# Remote shutdown enabled
endpoints:
  shutdown:
    enabled: true
