# Production environment

spring:
  # Cache configuration
  resources:
    cache-period: 3600
  # Local database
  datasource:
    # Tomcat specific pool configuration
    # #234 Make sure the connections are renewed in the pool
    maxAge: 600000

# SSL configuration
server:
  port: 443
  ssl:
    enabled: true
    key-alias: ontrack
    key-store: "config/keystore.p12"
    key-store-type: PKCS12
    key-store-password: ontrack
    key-password: ontrack
