site_name: !ENV [ YONTRACK_DOCS_TITLE, 'Local Yontrack documentation' ]
theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: material
  # Customization
  logo: img/yontrack-logo.svg
  favicon: img/favicon.ico
  palette:
    scheme: yontrack
  font:
    text: Hanken Grotesk
use_directory_urls: false
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - macros:
      on_error_fail: false
      on_undefined: strict
extra:
  yontrack_version: !ENV [ YONTRACK_VERSION, 'dev' ]
  ontrack_github_actions_cli_config_version: 1.0.3
  ontrack_cli_version: 5.0.0-beta+002
nav:
  - Home: index.md
  - Getting started:
      - Installation: content/start/getting-started.md
      - Configuration: content/start/configuration.md
  - Security:
      - OIDC: content/security/oidc.md
      - LDAP: content/security/ldap.md
      - Roles: content/security/roles.md
      - Groups: content/security/groups.md
      - Group mappings: content/security/group-mappings.md
      - Tokens: content/security/tokens.md
  - Integrations:
      - Notifications:
          - Overview: content/integrations/notifications/index.md
          - Jenkins: content/integrations/notifications/jenkins.md
  - Reference:
      - Configuration properties: content/generated/configurations/index.md
      - Event types: content/generated/events/index.md
      - Notification channels: content/generated/notifications/index.md
  - Appendix:
      - CI Configuration: content/appendix/ci-config.md
      - Configuration as Code: content/appendix/casc.md
      - Migration from V4: content/appendix/migration-from-v4.md
