services:

  # Database
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ontrack
      POSTGRES_USER: ontrack
      POSTGRES_PASSWORD: ontrack
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: http://localhost:8008
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    ports:
      - "8008:8080"
    command:
      - start
      - --import-realm
    volumes:
      - ./keycloak/import/oidc:/opt/keycloak/data/import
      - ./keycloak/themes/yontrack:/opt/keycloak/themes/yontrack

  rabbitmq:
    image: rabbitmq:4.1.3-management
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ontrack
      RABBITMQ_DEFAULT_PASS: ontrack
    ports:
      - "15672:15672"
      - "5672:5672"

  ontrack:
    image: "nemerosa/ontrack:${ONTRACK_VERSION:-latest}"
    ports:
      - "8080:8080"
      - "8800:8800"
    depends_on:
      postgres:
        condition: service_started
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_started
      keycloak:
        condition: service_started
    environment:
      # Development configuration
      SPRING_PROFILES_ACTIVE: dev

      ############################################################
      # Configuration of Ontrack
      ############################################################

      # General configuration
      JAVA_OPTIONS: "-Xmx2048m -Xms2048m"

      # Database
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/ontrack"

      # Elastic search
      ONTRACK_CONFIG_SEARCH_INDEX_IMMEDIATE: "true"
      SPRING_ELASTICSEARCH_URIS: "http://elasticsearch:9200"

      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ontrack
      SPRING_RABBITMQ_PASSWORD: ontrack

      # Authentication
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8008/realms/ontrack
      # We need to skip the host verification (keycloak vs. localhost)
      # DO NOT USE IN PRODUCTION
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/ontrack/protocol/openid-connect/certs

      ############################################################
      # Configuration for the tests
      ############################################################

      # ... account tokens can be provisioned
      MANAGEMENT_ENDPOINT_ACCOUNT_ACCESS: unrestricted
      # ... configurations are not tested
      ONTRACK_CONFIG_CONFIGURATION_TEST: "false"
      # ... GitHub ingestion specifics
      ONTRACK_EXTENSION_GITHUB_INGESTION_HOOK_SIGNATURE_DISABLED: true
      # ... Jira in mock mode
      ONTRACK_EXTENSION_JIRA_CLIENT_TYPE: mock

  ui:
    image: "nemerosa/ontrack-ui:${ONTRACK_VERSION:-latest}"
    ports:
      - "3000:3000"
    environment:
      ONTRACK_URL: http://ontrack:8080
      NEXTAUTH_SECRET: d18828b20e2a036cc3091959f13bdc080314ff5c3bae4
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_PROVIDER: oidc
      NEXTAUTH_ISSUER: http://keycloak:8080/realms/ontrack
      NEXTAUTH_CLIENT_ID: ontrack-client
      NEXTAUTH_CLIENT_SECRET: ontrack-client-secret
      NEXTAUTH_ACCOUNT_URL: http://localhost:8008/realms/ontrack/account
    depends_on:
      ontrack:
        condition: service_started
      keycloak:
        condition: service_started
