site_name: Yontrack documentation
theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: material
  # Customization
  logo: img/yontrack-logo.svg
  favicon: img/favicon.ico
  palette:
    scheme: yontrack
  font:
    text: Hanken Grotesk
use_directory_urls: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
plugins:
  - macros:
      on_error_fail: false
      on_undefined: strict
extra:
  version: !ENV [VERSION, 'local']  # Second value is the default
nav:
  - Home: index.md
  - Getting started:
      - Installation: content/start/getting-started.md
      - Configuration: content/start/configuration.md
