[project]
name = "yontrack-docs"
version = "0.1.0"
description = "Yontrack documentation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
    "pymdown-extensions>=10.17.2",
]
